Desktop adaptation
redmarverick/Portfolio pull request #4
Opened 2023-03-30 05:08 UTC by redmarverick

- Change of size of font inside lang-item, so you can make it smaller without leaving its container 
- removed last name input

The previous changes were accepted by reviwers on https://github.com/redmarverick/Portfolio/pull/3
Please take that in consideration before asking new changes.

2023-03-30 05:42 UTC, zieeco requested changes
Hi @redmarverick,

<img height="230" src="https://media0.giphy.com/media/bGCwmLDnwL25kCg3FV/giphy-downsized-medium.gif"/>

Great work job so far! 👏 
You've done well, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice design. ✔️
- Descriptive PR. ✔️
- Good commit message :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._


## Optional suggestions
- N/A

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-30 05:42 UTC, zieeco commented on styles.css
### WORKS SECTION


- Hey, your work's section seems to overlap with the image in the first section. please, kindly improve the design. see the image below:


*your design*
![Screenshot from 2023-03-30 06-12-20](https://user-images.githubusercontent.com/59397159/228737458-1ae4cbdf-c2af-4d43-b33b-e7d64afba86f.png)

*Figma design*
![Screenshot from 2023-03-30 06-25-44](https://user-images.githubusercontent.com/59397159/228737891-cfbb17de-8b0d-4d4c-a24f-3a15f22b8358.png)

2023-03-30 05:42 UTC, zieeco commented on styles.css
### ABOUT SECTION 


- Hey, also, there should be space between the paragraph and the background image. see the image below to improve the design of this section:


*your design*
![Screenshot from 2023-03-30 06-13-59](https://user-images.githubusercontent.com/59397159/228737618-023bdfb3-cc0a-409e-bbc3-01e714c6f294.png)


*Figma design*
![Screenshot from 2023-03-30 06-27-55](https://user-images.githubusercontent.com/59397159/228738567-11dcdb83-72c0-4fec-9b8a-c18dcff2f4bb.png)

2023-03-30 05:42 UTC, zieeco commented on styles.css
### ABOUT LANGUAGE LIST


- Hey, let's also improve the design on this card as the contents are coming out of the card. see the image below to improve your design:

*Figma design*
![Screenshot from 2023-03-30 06-33-48](https://user-images.githubusercontent.com/59397159/228739427-e9fd05e0-4b4b-472d-9ace-27508800ee8c.png)

*Your design*
![Screenshot from 2023-03-30 06-33-28](https://user-images.githubusercontent.com/59397159/228739429-99f99f30-0b4a-4b48-8566-8b71a1d835b2.png)
*your design*
![Screenshot from 2023-03-30 06-38-20](https://user-images.githubusercontent.com/59397159/228739788-25f26bc1-bab4-4921-a186-b8e22a782e14.png)

2023-03-31 23:19 UTC, braincee approved these changes
Hi @redmarverick, I am @braincee, your Code Reviewer.

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

![youre-approved-shirley-auto-group](https://user-images.githubusercontent.com/78104544/226852457-95ef4c1d-5d51-4f76-abd8-1fdc06b89e77.gif)

OPTIONAL CHANGES
---

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @braincee._

---

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-04-01 00:48 UTC, merged